app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$uploadFile(count1 = "pancreatic_ductal_adenocarcinoma_hs_raw_counts.txt") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$uploadFile(phenotype1 = "pancreatic_ductal_adenocarcinoma_hs_pheno.txt") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(start = "click")
app$snapshot()
app$snapshot()
app$setInputs(Atlas_ids = "E-MTAB-4054")
app$setInputs(Atlas_run = "click")
app$setInputs(volcano_col = "4054")
app$setInputs(experiment_id = "4054")
app$setInputs(log_scale = TRUE)
app$setInputs(volcano_col = "pad")
app$setInputs(volcano_col = "padj")
app$snapshot()
app$setInputs(col_low = "mh")
app$setInputs(col_low = "yelow")
app$setInputs(col_low = "yellow")
app$snapshot()
